# Generated by Django 2.2.3 on 2019-10-17 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=70)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.TextField()),
            ],
        ),
    ]
