# Generated by Django 2.2.3 on 2019-10-17 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bytetrekapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='BytetrekUser',
        ),
    ]
